{
  "formatVersion": "1.1",
  "component": {
    "group": "com.axelor",
    "module": "axelor-gradle",
    "version": "5.4.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "wraqs73utbgepbh5quwfwwse2u"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.axelor",
          "module": "axelor-tomcat",
          "version": {
            "requires": "5.4.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "axelor-gradle-5.4.0-SNAPSHOT.jar",
          "url": "axelor-gradle-5.4.0-SNAPSHOT.jar",
          "size": 254085,
          "sha512": "c9411d26da9d70326e021019a37f4dc29f8cb10c57c8d78b2013e0446b0e85d4f59e364e5856b82ffa2887f6a5b01419fe259863c9b84e2b39a88fcf77f4bac0",
          "sha256": "df6e288e95e7dcb6107063152a084bae62fdc61ac9e69dee1227f9551a0dbe7a",
          "sha1": "492913e7830a191521bdc021bddb8529f5762d67",
          "md5": "ebfd673dbcc29a159430b020b9e2dae7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.25"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "jul-to-slf4j",
          "version": {
            "requires": "1.7.25"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "jcl-over-slf4j",
          "version": {
            "requires": "1.7.25"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "log4j-over-slf4j",
          "version": {
            "requires": "1.7.25"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-core",
          "version": {
            "requires": "1.2.3"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.2.3"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "org.fusesource.jansi",
          "module": "jansi",
          "version": {
            "requires": "1.15"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "com.axelor",
          "module": "axelor-common",
          "version": {
            "requires": "5.4.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.1-jre"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "com.opencsv",
          "module": "opencsv",
          "version": {
            "requires": "3.9"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "gradle.plugin.nl.javadude.gradle.plugins",
          "module": "license-gradle-plugin",
          "version": {
            "requires": "0.14.0"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.25"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "com.axelor",
          "module": "axelor-tomcat",
          "version": {
            "requires": "5.4.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "axelor-gradle-5.4.0-SNAPSHOT.jar",
          "url": "axelor-gradle-5.4.0-SNAPSHOT.jar",
          "size": 254085,
          "sha512": "c9411d26da9d70326e021019a37f4dc29f8cb10c57c8d78b2013e0446b0e85d4f59e364e5856b82ffa2887f6a5b01419fe259863c9b84e2b39a88fcf77f4bac0",
          "sha256": "df6e288e95e7dcb6107063152a084bae62fdc61ac9e69dee1227f9551a0dbe7a",
          "sha1": "492913e7830a191521bdc021bddb8529f5762d67",
          "md5": "ebfd673dbcc29a159430b020b9e2dae7"
        }
      ]
    }
  ]
}
