{
  "formatVersion": "1.1",
  "component": {
    "group": "com.axelor",
    "module": "axelor-test",
    "version": "5.4.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "wraqs73utbgepbh5quwfwwse2u"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.12"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "axelor-test-5.4.0-SNAPSHOT.jar",
          "url": "axelor-test-5.4.0-SNAPSHOT.jar",
          "size": 11802,
          "sha512": "7c5f34c450d9d6eaba5ffdf2eb69c6cb0ba4015832eb93271ab29f9f450d423fcb5435427601df7c4780488d616776518061cbca3591bd07d75adc0023e52de5",
          "sha256": "4e75a948554ed8c5aec00da6df49044ed2613b77f4e37975c5a3f5ce61cd8c5b",
          "sha1": "9c8da95f136987ab7197bd1dcf30cb98ba9725dc",
          "md5": "bc514097a78dbb4f42f3719781635691"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.25"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "jul-to-slf4j",
          "version": {
            "requires": "1.7.25"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "jcl-over-slf4j",
          "version": {
            "requires": "1.7.25"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "log4j-over-slf4j",
          "version": {
            "requires": "1.7.25"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-core",
          "version": {
            "requires": "1.2.3"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.2.3"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "org.fusesource.jansi",
          "module": "jansi",
          "version": {
            "requires": "1.15"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "4.2.2"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "com.google.inject.extensions",
          "module": "guice-servlet",
          "version": {
            "requires": "4.2.2"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "com.google.inject.extensions",
          "module": "guice-persist",
          "version": {
            "requires": "4.2.2"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "org.hsqldb",
          "module": "hsqldb",
          "version": {
            "requires": "2.3.4"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "org.postgresql",
          "module": "postgresql",
          "version": {
            "requires": "42.0.0"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "org.hibernate",
          "module": "hibernate-core",
          "version": {
            "requires": "5.2.10.Final"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "org.hibernate",
          "module": "hibernate-hikaricp",
          "version": {
            "requires": "5.2.10.Final"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "org.hibernate",
          "module": "hibernate-validator",
          "version": {
            "requires": "5.4.1.Final"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "org.hibernate",
          "module": "hibernate-ehcache",
          "version": {
            "requires": "5.2.10.Final"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "org.hibernate",
          "module": "hibernate-jcache",
          "version": {
            "requires": "5.2.10.Final"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "org.hibernate",
          "module": "hibernate-entitymanager",
          "version": {
            "requires": "5.2.10.Final"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "org.jboss.resteasy",
          "module": "resteasy-jaxrs",
          "version": {
            "requires": "3.1.2.Final"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "org.jboss.resteasy",
          "module": "resteasy-jackson2-provider",
          "version": {
            "requires": "3.1.2.Final"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "org.jboss.resteasy",
          "module": "resteasy-servlet-initializer",
          "version": {
            "requires": "3.1.2.Final"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "org.jboss.resteasy",
          "module": "resteasy-guice",
          "version": {
            "requires": "3.1.2.Final"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "org.jboss.resteasy",
          "module": "resteasy-client",
          "version": {
            "requires": "3.1.2.Final"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "org.jboss.resteasy",
          "module": "resteasy-undertow",
          "version": {
            "requires": "3.1.2.Final"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "io.undertow",
          "module": "undertow-core",
          "version": {
            "requires": "1.4.4.Final"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "io.undertow",
          "module": "undertow-servlet",
          "version": {
            "requires": "1.4.4.Final"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.8.8"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.8.8"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.8.8"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.jaxrs",
          "module": "jackson-jaxrs-json-provider",
          "version": {
            "requires": "2.8.8"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-guava",
          "version": {
            "requires": "2.8.8"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-parameter-names",
          "version": {
            "requires": "2.8.8"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.8.8"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jdk8",
          "version": {
            "requires": "2.8.8"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.12"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "axelor-test-5.4.0-SNAPSHOT.jar",
          "url": "axelor-test-5.4.0-SNAPSHOT.jar",
          "size": 11802,
          "sha512": "7c5f34c450d9d6eaba5ffdf2eb69c6cb0ba4015832eb93271ab29f9f450d423fcb5435427601df7c4780488d616776518061cbca3591bd07d75adc0023e52de5",
          "sha256": "4e75a948554ed8c5aec00da6df49044ed2613b77f4e37975c5a3f5ce61cd8c5b",
          "sha1": "9c8da95f136987ab7197bd1dcf30cb98ba9725dc",
          "md5": "bc514097a78dbb4f42f3719781635691"
        }
      ]
    }
  ]
}
