{
  "formatVersion": "1.1",
  "component": {
    "group": "com.axelor",
    "module": "axelor-core",
    "version": "5.4.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "wraqs73utbgepbh5quwfwwse2u"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.tika",
          "module": "tika-parsers",
          "version": {
            "requires": "1.4"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            },
            {
              "group": "rome",
              "module": "rome"
            },
            {
              "group": "org.gagravarr",
              "module": "vorbis-java-tika"
            },
            {
              "group": "org.bouncycastle",
              "module": "bcmail-jdk15"
            },
            {
              "group": "edu.ucar",
              "module": "netcdf"
            },
            {
              "group": "xerces",
              "module": "xercesImpl"
            },
            {
              "group": "org.gagravarr",
              "module": "vorbis-java-core"
            },
            {
              "group": "org.apache.james",
              "module": "apache-mime4j-dom"
            },
            {
              "group": "org.ow2.asm",
              "module": "asm-debug-all"
            },
            {
              "group": "com.googlecode.mp4parser",
              "module": "isoparser"
            },
            {
              "group": "org.apache.james",
              "module": "apache-mime4j-core"
            },
            {
              "group": "org.bouncycastle",
              "module": "bcprov-jdk15"
            },
            {
              "group": "org.apache.geronimo.specs",
              "module": "geronimo-stax-api_1.0_spec"
            }
          ]
        },
        {
          "group": "com.axelor",
          "module": "axelor-common",
          "version": {
            "requires": "5.4.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy-all",
          "version": {
            "requires": "2.4.10"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "groovy-all",
              "type": "jar",
              "extension": "jar",
              "classifier": "indy"
            }
          }
        },
        {
          "group": "com.github.groovy-wslite",
          "module": "groovy-wslite",
          "version": {
            "requires": "1.1.2"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            },
            {
              "group": "org.codehaus.groovy",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.1-jre"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "4.2.2"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "com.google.inject.extensions",
          "module": "guice-servlet",
          "version": {
            "requires": "4.2.2"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "com.google.inject.extensions",
          "module": "guice-persist",
          "version": {
            "requires": "4.2.2"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "com.google.inject.extensions",
          "module": "guice-multibindings",
          "version": {
            "requires": "4.2.2"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "org.hibernate",
          "module": "hibernate-core",
          "version": {
            "requires": "5.2.10.Final"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "org.hibernate",
          "module": "hibernate-hikaricp",
          "version": {
            "requires": "5.2.10.Final"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "org.hibernate",
          "module": "hibernate-validator",
          "version": {
            "requires": "5.4.1.Final"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "org.hibernate",
          "module": "hibernate-ehcache",
          "version": {
            "requires": "5.2.10.Final"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "org.hibernate",
          "module": "hibernate-jcache",
          "version": {
            "requires": "5.2.10.Final"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "org.hibernate",
          "module": "hibernate-entitymanager",
          "version": {
            "requires": "5.2.10.Final"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "org.jboss.resteasy",
          "module": "resteasy-jaxrs",
          "version": {
            "requires": "3.1.2.Final"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "org.jboss.resteasy",
          "module": "resteasy-jackson2-provider",
          "version": {
            "requires": "3.1.2.Final"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "org.jboss.resteasy",
          "module": "resteasy-servlet-initializer",
          "version": {
            "requires": "3.1.2.Final"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "org.jboss.resteasy",
          "module": "resteasy-guice",
          "version": {
            "requires": "3.1.2.Final"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.8.8"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.8.8"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.8.8"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.jaxrs",
          "module": "jackson-jaxrs-json-provider",
          "version": {
            "requires": "2.8.8"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-guava",
          "version": {
            "requires": "2.8.8"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-parameter-names",
          "version": {
            "requires": "2.8.8"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.8.8"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jdk8",
          "version": {
            "requires": "2.8.8"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "org.antlr",
          "module": "ST4",
          "version": {
            "requires": "4.0.8"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "org.apache.shiro",
          "module": "shiro-core",
          "version": {
            "requires": "1.4.1"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "org.apache.shiro",
          "module": "shiro-web",
          "version": {
            "requires": "1.4.1"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "org.apache.shiro",
          "module": "shiro-guice",
          "version": {
            "requires": "1.4.1"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "com.thoughtworks.xstream",
          "module": "xstream",
          "version": {
            "requires": "1.4.11.1"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "com.fasterxml.woodstox",
          "module": "woodstox-core",
          "version": {
            "requires": "5.3.0"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "com.opencsv",
          "module": "opencsv",
          "version": {
            "requires": "3.9"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "javax.servlet",
          "module": "javax.servlet-api",
          "version": {
            "requires": "3.1.0"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "com.sun.mail",
          "module": "javax.mail",
          "version": {
            "requires": "1.5.6"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "org.quartz-scheduler",
          "module": "quartz",
          "version": {
            "requires": "2.2.3"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            },
            {
              "group": "*",
              "module": "c3p0"
            }
          ]
        },
        {
          "group": "org.eclipse.birt.runtime",
          "module": "org.eclipse.birt.runtime",
          "version": {
            "requires": "4.4.2"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            },
            {
              "group": "*",
              "module": "commons-cli"
            },
            {
              "group": "*",
              "module": "org.apache.batik.pdf"
            },
            {
              "group": "*",
              "module": "derby"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "axelor-core-5.4.0-SNAPSHOT.jar",
          "url": "axelor-core-5.4.0-SNAPSHOT.jar",
          "size": 4061419,
          "sha512": "22ca2c7883fbda9b4d8d87daa800306db8ed8280009ebe73034c6cbaa4f54d91ad9298cb65c0977043c38f0f73a520c42722acdec86d16959b36dbf4425d90fc",
          "sha256": "fe22b05d77fa351223fe786b7ec0ac65f3497cb6e97b414d4c45bbf0428825c0",
          "sha1": "5682cd3b1fc816d27cac5efdf089daeb562674eb",
          "md5": "99525817f36df9bcc0e678eb42b129ff"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.25"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "jul-to-slf4j",
          "version": {
            "requires": "1.7.25"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "jcl-over-slf4j",
          "version": {
            "requires": "1.7.25"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "log4j-over-slf4j",
          "version": {
            "requires": "1.7.25"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-core",
          "version": {
            "requires": "1.2.3"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.2.3"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "org.fusesource.jansi",
          "module": "jansi",
          "version": {
            "requires": "1.15"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "com.axelor",
          "module": "axelor-asm",
          "version": {
            "requires": "5.2"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "org.hotswapagent",
          "module": "hotswap-agent-core",
          "version": {
            "requires": "1.3.0"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "org.hotswapagent",
          "module": "hotswap-agent-tomcat-plugin",
          "version": {
            "requires": "1.3.0"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "org.hotswapagent",
          "module": "hotswap-agent-logback-plugin",
          "version": {
            "requires": "1.3.0"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "org.hotswapagent",
          "module": "hotswap-agent-proxy-plugin",
          "version": {
            "requires": "1.3.0"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "com.axelor",
          "module": "axelor-tomcat",
          "version": {
            "requires": "5.4.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "net.bytebuddy",
          "module": "byte-buddy",
          "version": {
            "requires": "1.6.14"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "org.postgresql",
          "module": "postgresql",
          "version": {
            "requires": "42.0.0"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "mysql",
          "module": "mysql-connector-java",
          "version": {
            "requires": "5.1.41"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "org.hibernate",
          "module": "hibernate-search-orm",
          "version": {
            "requires": "5.7.0.Final"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "org.apache.tika",
          "module": "tika-core",
          "version": {
            "requires": "1.4"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "org.flywaydb",
          "module": "flyway-core",
          "version": {
            "requires": "4.1.2"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.25"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "com.axelor",
          "module": "axelor-el",
          "version": {
            "requires": "8.5.54"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.10.2"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "org.eclipse.persistence",
          "module": "org.eclipse.persistence.moxy",
          "version": {
            "requires": "2.6.4"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "io.buji",
          "module": "buji-pac4j",
          "version": {
            "requires": "4.1.1"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "org.pac4j",
          "module": "pac4j-oidc",
          "version": {
            "requires": "3.8.3"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            },
            {
              "group": "org.mockito",
              "module": "mockito-core"
            }
          ]
        },
        {
          "group": "org.pac4j",
          "module": "pac4j-oauth",
          "version": {
            "requires": "3.8.3"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "org.pac4j",
          "module": "pac4j-saml",
          "version": {
            "requires": "3.8.3"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "org.pac4j",
          "module": "pac4j-cas",
          "version": {
            "requires": "3.8.3"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "org.pac4j",
          "module": "pac4j-http",
          "version": {
            "requires": "3.8.3"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "org.pac4j",
          "module": "pac4j-ldap",
          "version": {
            "requires": "3.8.3"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "org.ldaptive",
          "module": "ldaptive",
          "version": {
            "requires": "1.2.4"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "commons-jxpath",
          "module": "commons-jxpath",
          "version": {
            "requires": "1.3"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "com.beust",
          "module": "jcommander",
          "version": {
            "requires": "1.71"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "com.axelor",
          "module": "axelor-common",
          "version": {
            "requires": "5.4.0-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "org.codehaus.groovy",
          "module": "groovy-all",
          "version": {
            "requires": "2.4.10"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "groovy-all",
              "type": "jar",
              "extension": "jar",
              "classifier": "indy"
            }
          }
        },
        {
          "group": "com.github.groovy-wslite",
          "module": "groovy-wslite",
          "version": {
            "requires": "1.1.2"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            },
            {
              "group": "org.codehaus.groovy",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "28.1-jre"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "4.2.2"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "com.google.inject.extensions",
          "module": "guice-servlet",
          "version": {
            "requires": "4.2.2"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "com.google.inject.extensions",
          "module": "guice-persist",
          "version": {
            "requires": "4.2.2"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "com.google.inject.extensions",
          "module": "guice-multibindings",
          "version": {
            "requires": "4.2.2"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "org.hibernate",
          "module": "hibernate-core",
          "version": {
            "requires": "5.2.10.Final"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "org.hibernate",
          "module": "hibernate-hikaricp",
          "version": {
            "requires": "5.2.10.Final"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "org.hibernate",
          "module": "hibernate-validator",
          "version": {
            "requires": "5.4.1.Final"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "org.hibernate",
          "module": "hibernate-ehcache",
          "version": {
            "requires": "5.2.10.Final"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "org.hibernate",
          "module": "hibernate-jcache",
          "version": {
            "requires": "5.2.10.Final"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "org.hibernate",
          "module": "hibernate-entitymanager",
          "version": {
            "requires": "5.2.10.Final"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "org.jboss.resteasy",
          "module": "resteasy-jaxrs",
          "version": {
            "requires": "3.1.2.Final"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "org.jboss.resteasy",
          "module": "resteasy-jackson2-provider",
          "version": {
            "requires": "3.1.2.Final"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "org.jboss.resteasy",
          "module": "resteasy-servlet-initializer",
          "version": {
            "requires": "3.1.2.Final"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "org.jboss.resteasy",
          "module": "resteasy-guice",
          "version": {
            "requires": "3.1.2.Final"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.8.8"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.8.8"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.8.8"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.jaxrs",
          "module": "jackson-jaxrs-json-provider",
          "version": {
            "requires": "2.8.8"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-guava",
          "version": {
            "requires": "2.8.8"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-parameter-names",
          "version": {
            "requires": "2.8.8"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.8.8"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jdk8",
          "version": {
            "requires": "2.8.8"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "org.antlr",
          "module": "ST4",
          "version": {
            "requires": "4.0.8"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "org.apache.shiro",
          "module": "shiro-core",
          "version": {
            "requires": "1.4.1"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "org.apache.shiro",
          "module": "shiro-web",
          "version": {
            "requires": "1.4.1"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "org.apache.shiro",
          "module": "shiro-guice",
          "version": {
            "requires": "1.4.1"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "com.thoughtworks.xstream",
          "module": "xstream",
          "version": {
            "requires": "1.4.11.1"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "com.fasterxml.woodstox",
          "module": "woodstox-core",
          "version": {
            "requires": "5.3.0"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "com.opencsv",
          "module": "opencsv",
          "version": {
            "requires": "3.9"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "javax.servlet",
          "module": "javax.servlet-api",
          "version": {
            "requires": "3.1.0"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "com.sun.mail",
          "module": "javax.mail",
          "version": {
            "requires": "1.5.6"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "org.quartz-scheduler",
          "module": "quartz",
          "version": {
            "requires": "2.2.3"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            },
            {
              "group": "*",
              "module": "c3p0"
            }
          ]
        },
        {
          "group": "org.eclipse.birt.runtime",
          "module": "org.eclipse.birt.runtime",
          "version": {
            "requires": "4.4.2"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            },
            {
              "group": "*",
              "module": "commons-cli"
            },
            {
              "group": "*",
              "module": "org.apache.batik.pdf"
            },
            {
              "group": "*",
              "module": "derby"
            }
          ]
        },
        {
          "group": "org.apache.tika",
          "module": "tika-parsers",
          "version": {
            "requires": "1.4"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            },
            {
              "group": "rome",
              "module": "rome"
            },
            {
              "group": "org.gagravarr",
              "module": "vorbis-java-tika"
            },
            {
              "group": "org.bouncycastle",
              "module": "bcmail-jdk15"
            },
            {
              "group": "edu.ucar",
              "module": "netcdf"
            },
            {
              "group": "xerces",
              "module": "xercesImpl"
            },
            {
              "group": "org.gagravarr",
              "module": "vorbis-java-core"
            },
            {
              "group": "org.apache.james",
              "module": "apache-mime4j-dom"
            },
            {
              "group": "org.ow2.asm",
              "module": "asm-debug-all"
            },
            {
              "group": "com.googlecode.mp4parser",
              "module": "isoparser"
            },
            {
              "group": "org.apache.james",
              "module": "apache-mime4j-core"
            },
            {
              "group": "org.bouncycastle",
              "module": "bcprov-jdk15"
            },
            {
              "group": "org.apache.geronimo.specs",
              "module": "geronimo-stax-api_1.0_spec"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "axelor-core-5.4.0-SNAPSHOT.jar",
          "url": "axelor-core-5.4.0-SNAPSHOT.jar",
          "size": 4061419,
          "sha512": "22ca2c7883fbda9b4d8d87daa800306db8ed8280009ebe73034c6cbaa4f54d91ad9298cb65c0977043c38f0f73a520c42722acdec86d16959b36dbf4425d90fc",
          "sha256": "fe22b05d77fa351223fe786b7ec0ac65f3497cb6e97b414d4c45bbf0428825c0",
          "sha1": "5682cd3b1fc816d27cac5efdf089daeb562674eb",
          "md5": "99525817f36df9bcc0e678eb42b129ff"
        }
      ]
    }
  ]
}
